[[SQLCipher]]
arch = "aarch64"
git-tree-sha1 = "13d1d74caa0b118ccc1ed5018a1c813d65c644fa"
os = "macos"

    [[SQLCipher.download]]
    sha256 = "3955fd790b064923ce502a0fc11248e1aff899274a92b710cb6ebf11be9def92"
    url = "https://github.com/JuliaBinaryWrappers/SQLCipher_jll.jl/releases/download/SQLCipher-v4.5.0+0/SQLCipher.v4.5.0.aarch64-apple-darwin.tar.gz"
[[SQLCipher]]
arch = "aarch64"
git-tree-sha1 = "005e7ba8f103451d42804cd49b09e56e07f0a1b9"
libc = "glibc"
os = "linux"

    [[SQLCipher.download]]
    sha256 = "f94033f40d09699a516d991c41ef81fd35cbe21ea187ee9d7cbd7e5b1f4ab54a"
    url = "https://github.com/JuliaBinaryWrappers/SQLCipher_jll.jl/releases/download/SQLCipher-v4.5.0+0/SQLCipher.v4.5.0.aarch64-linux-gnu.tar.gz"
[[SQLCipher]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "03f8825ed01178a397e2565c66942e0971685fc1"
libc = "glibc"
os = "linux"

    [[SQLCipher.download]]
    sha256 = "0b65ed8088247b3f65c641d84d0eb187f74776e4b682ee0655801d743bb94663"
    url = "https://github.com/JuliaBinaryWrappers/SQLCipher_jll.jl/releases/download/SQLCipher-v4.5.0+0/SQLCipher.v4.5.0.armv6l-linux-gnueabihf.tar.gz"
[[SQLCipher]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a5a189ca3da5b13a60ca9b9387d27710f92ce7d4"
libc = "glibc"
os = "linux"

    [[SQLCipher.download]]
    sha256 = "579ec3020d7d682733f1cec7cc00fb85474f8a408c6a19b17c042ca5d2670f7b"
    url = "https://github.com/JuliaBinaryWrappers/SQLCipher_jll.jl/releases/download/SQLCipher-v4.5.0+0/SQLCipher.v4.5.0.armv7l-linux-gnueabihf.tar.gz"
[[SQLCipher]]
arch = "i686"
git-tree-sha1 = "5f1498ef100c22e45dbe3fbcf8d8b677b70ec17b"
libc = "glibc"
os = "linux"

    [[SQLCipher.download]]
    sha256 = "20a4d1b21043c01f7303595f909c29794ef199f1bdd1caf751856e1b44d9f655"
    url = "https://github.com/JuliaBinaryWrappers/SQLCipher_jll.jl/releases/download/SQLCipher-v4.5.0+0/SQLCipher.v4.5.0.i686-linux-gnu.tar.gz"
[[SQLCipher]]
arch = "powerpc64le"
git-tree-sha1 = "970219fb81334c357734ac73839767c26bf71ee5"
libc = "glibc"
os = "linux"

    [[SQLCipher.download]]
    sha256 = "29f613bd932f45ca765a8fb9425f2a58e02983eca235b29d60d614c6c78b7c40"
    url = "https://github.com/JuliaBinaryWrappers/SQLCipher_jll.jl/releases/download/SQLCipher-v4.5.0+0/SQLCipher.v4.5.0.powerpc64le-linux-gnu.tar.gz"
[[SQLCipher]]
arch = "x86_64"
git-tree-sha1 = "4b75af74bc3d3ac08bb9008f291486cbfcc7bd2e"
os = "macos"

    [[SQLCipher.download]]
    sha256 = "712a85c6798f8a4c0f87dd89fbdb85eb32cc6325ea6a4b901ca3a506b485a8e5"
    url = "https://github.com/JuliaBinaryWrappers/SQLCipher_jll.jl/releases/download/SQLCipher-v4.5.0+0/SQLCipher.v4.5.0.x86_64-apple-darwin.tar.gz"
[[SQLCipher]]
arch = "x86_64"
git-tree-sha1 = "37ffb20e4e57a6c54ecc68ac28fd2eb5a0b9ff15"
libc = "glibc"
os = "linux"

    [[SQLCipher.download]]
    sha256 = "b2de541ae12e705b49a64cb5414f16735b7f9ec990aefa16abfb298eba3690a0"
    url = "https://github.com/JuliaBinaryWrappers/SQLCipher_jll.jl/releases/download/SQLCipher-v4.5.0+0/SQLCipher.v4.5.0.x86_64-linux-gnu.tar.gz"
