# Autogenerated wrapper script for SQLCipher_jll for powerpc64le-linux-gnu
export libsqlcipher, sqlcipher

using OpenSSL_jll
JLLWrappers.@generate_wrapper_header("SQLCipher")
JLLWrappers.@declare_library_product(libsqlcipher, "libsqlcipher.so.0")
JLLWrappers.@declare_executable_product(sqlcipher)
function __init__()
    JLLWrappers.@generate_init_header(OpenSSL_jll)
    JLLWrappers.@init_library_product(
        libsqlcipher,
        "lib/libsqlcipher.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        sqlcipher,
        "bin/sqlcipher",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
